development:
  adapter: postgresql
  encoding: unicode
  database: reading_list_dev
  host: localhost
  pool: 5
  username: postgres
  password:
  timeout: 5000
# Test environment
test:
  adapter: postgresql
  encoding: unicode
  database: reading_list_test
  host: localhost
  pool: 5
  username: postgres
  password:
  timeout: 5000
# Production
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: reading_list_prod
  pool: 5
  username: postgres
  password:
  timeout: 5000